name: formio_flutter
description: A flutter package to let users consume any form created with formIO.js
version: 0.9.40
homepage: https://github.com/Crdzbird/formio_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^4.3.3
  rxdart: ^0.25.0
  http: ^0.12.2
  image: ^2.1.19
  math_expressions: ^2.0.2
  file_picker: ^2.1.6
  flutter_neumorphic: ^3.0.3
  font_awesome_flutter: ^8.11.0
  assorted_layout_widgets: ^4.0.1
  universal_io: ^1.0.2
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
